name: HotspotPlugin
version: '${version}'
main: org.capy.hotspotplugin.HotspotPlugin
api-version: '1.20'
commands:
  hotspot:
    description: teleport to a hotspot
    usage: /hotspot [create]
    permission: "hotspotplugin.tp"